### ISSUE TITLE
Add log aggregation

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul-collections#107]
## Acceptance Criteria

- [ ] There's a place to go to look at all logs for DPUL Collections in staging.
- [ ] The logs are searchable.
- [ ] it's documented in the readme

## First Step

Look at https://dev.to/justinepdevasia/docker-log-observability-analyzing-container-logs-in-hashicorp-nomad-with-vector-loki-and-grafana-4dp4

**Comment by tpendragon** [comment]
So we can't pay for Datadog for our staging boxes, so I think log aggregation here probably means implementing those little experiments I did around Grafana & Loki, like in https://dev.to/justinepdevasia/docker-log-observability-analyzing-container-logs-in-hashicorp-nomad-with-vector-loki-and-grafana-4dp4.

Otherwise we could probably add a console command to tail logs...maybe even all of them somehow.

**Comment by tpendragon** [comment]
https://github.com/tolitius/entail is a utility that would let us tail all logs for a job
