### ISSUE TITLE
Research: How should we set up our JS infrastructure?

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#114]
## Acceptance Criteria

- [ ] Research has been done on options for setting up our Javascript - answering questions like if we need (or should use) Vite, if we should use yarn, whether we want to continue using the built-in esbuild, and how we should lay our javascript out.
- [ ] The research has been presented to the team a discussion is had. An initial decision on our first step forward is made and put in this ticket.

## Use Cases

1. We should be able to add the lux header and footer without adding all of Vue & Lux in prod.

## First Step

Do some googlin'.

## Some background talking

We talked about how Phoenix already has esbuild, which is supposed to be tree-shaking, so if it that works we might not need another build system like Vite.

**Comment by hackartisan** [comment]
Decisions:
- stick with built-in esbuild until it becomes obvious that we need something else
- use yarn rather than npm, it seems to have better security guarantees
- javascript file layout: they go in `assets/js` and `app.js` is the entrypoint. we can organize them by function as we usually do. 

The lux header / footer question will be covered by #122
