### ISSUE TITLE
Reassess lux header / footer (Phase 2)

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul-collections#133]
follow up to #122 

The way we're pulling these in right now means we're delivering all of vue and lux to client machines. To make these packages smaller we'll have to set up a more complex build pipeline.

Is there some way to reduce the load without just using the html / styles directly and updating them when they change? If not, do we want to do that to avoid complexity and bandwidth use?

Note: If / when we change the approach here, we'd like to look at moving the header / footer into the app layout rather than the root layout

**Comment by eliotjordan** [comment]
Some observations:

1. Styling the header and footer to match the body of the page is more difficult and adds CSS overhead because Lux doesn't use tailwind. For example, if we want to the body of the page to match the default width of the header, we're going to have to do some tweaking.
2. There is no clear path at the moment for making dropdown elements work with LiveView without re-loading the page. For example, selecting a language from a drop down re-loads the page as it appends a query parameter to the url.

**Comment by sdellis** [comment]
Just thinking a bit on your observations, @eliotjordan : 

1. We can set a `maxWidth` attribute/prop on the LuxLibraryHeader and LuxLibraryFooter, which could be set to match the [Tailwind defaults](https://tailwindcss.com/docs/theme#screens).
2. [Javascript Interoperability Hooks](https://hexdocs.pm/phoenix_live_view/js-interop.html#client-server-communication) seem like a possible path forward for header menu items and Liveview.
