### ISSUE TITLE
Success Dashboard

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#14]
## Acceptance Criteria

- [ ] There's a page I go to and I can select a date range, and see the values over time (each day in that date range) for the below metrics within that date range. Also totals at the bottom.

## Tips

Maybe ask AUX if they have a way they'd want this to happen. Some tableau thingy?

If AUX doesn't have strong opinions, then we'll put it in Figgy as a report page.

There's a plausible API key in lastpass.

## First Step

Read the Plausible API documentation.

## Success Criteria

- [ ] I can easily look at a single place (or quickly gather) the values I need for these metrics:
    * Views per Visit
    * Visit Duration
    * Downloads
       * We want all downloads of Figgy resources, and be able to filter where people are getting to those downloads from. Generally we want downloads to come up.
    * Number of record pages in a visit
    * Number of sources visits are coming from
    * Bounce Rate
    * Feedback from reference survey
- [ ] Document how to view that place and the metrics they're meant to measure:
     * Number of downloads over a time period goes up.
        * We want all downloads of Figgy resources, and be able to filter where people are getting to those downloads from. Generally we want downloads to come up.
     * Number of clicks in a session goes up.
     * Number of sessions greater than 1 minute goes up.
     * Users link our data out to other sites and platforms; blogs, IIIF story builders
     * Bounce Rate
     * Reference / area librarians or curators (sorry don’t know all the titles) hear that someone used a resource, or help them find a resource they say will be useful.

**Comment by tpendragon** [comment]
Kate & Hector have some tips about this, I'm meeting w/ them next week.

**Comment by sdellis** [comment]
@tpendragon the Plausible API allows us to aggregate our stats for a custom date range, but it does not return values per day, only in aggregate. In order to meet the success criteria of this ticket, we would need to make a separate API call for each day in the given range. With this approach, a single report for a two year range would exceed our allotted requests for an hour. Another approach that @AminEdZare suggested might be a workaround is to do a daily pull of the Plausible data from the API, store it in the database, and then run our own custom queries for the report that would avoid the rate limit. Thoughts?

See below:

> API keys have a rate limit of 600 requests per hour by default. If you have special needs for more requests, please contact us to request more capacity.

**Comment by tpendragon** [comment]
Average for the time period is probably fine for now? I don't want to maintain a sidecar.
